version: 2
multi-ecosystem-groups:
  playwright-group:
    schedule:
      interval: daily
    open-pull-requests-limit: 5
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    patterns:
      - playwright-ruby-client
    labels:
      - Dependencies
    groups:
      govuk-frontend-libraries:
        patterns:
          - govuk-components
          - govuk_design_system_formbuilder
    multi-ecosystem-group: playwright-group
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    patterns:
      - playwright
    labels:
      - Dependencies
    groups:
      esbuild-group:
        patterns:
          - esbuild
          - "@esbuild/linux-x64"
          - "@esbuild/darwin-arm64"
    multi-ecosystem-group: playwright-group
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - Dependencies
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
