version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - Dependencies
    groups:
      govuk-frontend-libraries:
        patterns:
          - govuk-components
          - govuk_design_system_formbuilder
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - Dependencies
    groups:
      esbuild-group:
        patterns:
          - esbuild
          - "@esbuild/linux-x64"
          - "@esbuild/darwin-arm64"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - Dependencies
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
