"API Release Note":
  - changed-files:
    - any-glob-to-any-file:
      - "app/views/api/release_notes/release_notes.yml"

Devops:
  - changed-files:
    - any-glob-to-any-file:
      - ".github/*"
      - ".github/actions/**/*"
      - ".github/workflows/**/*"
      - "config/terraform/**/*"

Docker:
  - changed-files:
    - any-glob-to-any-file:
      - ".devcontainer/**/*"
      - "Dockerfile"

Documentation:
  - changed-files:
    - any-glob-to-any-file:
      - "documentation/**/*"
      - "README.md"
