---
inherit_from: .rubocop_todo.yml

plugins: 
  - rubocop-performance
  - rubocop-factory_bot

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml    

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.3.4

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Style/Lambda:
  EnforcedStyle: literal

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/Output:
  Exclude:
    - db/seeds*

Rails/SaveBang:
  Exclude:
    - app/services/**/*

Naming/MethodParameterName:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
