---
inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-factory_bot

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.4
  StringLiteralsFrozenByDefault: true

require:
  - ./.rubocop/cop/rspec_cops

RSpec/RequireRailsHelper:
  Enabled: true
  AutoCorrect: false
  Exclude:
    - "spec/spec_helper.rb"
    - "spec/rails_helper.rb"

# Otherwise it suggests the namespace "ec_ts"
RSpec/SpecFilePathFormat:
  CustomTransform:
    ECTs: ects

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    # Leave historical migrations untouched, new ones must use double quotes.
    - "db/migrate/20240926161243_add_tsvector_column_to_teachers_for_searching.rb"
    - "db/migrate/20241003132805_add_outcome_field_to_pending_induction_submission.rb"
    - "db/migrate/20241120163657_add_outcome_to_induction_period.rb"
    - "db/migrate/20241211115427_create_events.rb"
    - "db/migrate/20250114194121_add_trs_fields_to_teacher.rb"
    - "db/migrate/20250115105233_add_system_to_event_author_types.rb"
    - "db/migrate/20250130172854_add_unknown_and_pre_september_2021_induction_programmes.rb"
    - "db/migrate/20250214124432_remove_unqiue_index_from_appropriate_body_name.rb"
    - "db/migrate/20250227215422_add_programme_choices_to_schools.rb"
    - "db/migrate/20250719173448_add_training_programme_to_training_periods.rb"
    - "db/migrate/20250815142537_remove_training_programme_from_ect_at_school_periods.rb"
    - "db/migrate/20250319234928_add_type_to_appropriate_bodies.rb"
    - "db/migrate/20250324152652_create_pending_induction_submission_batches.rb"
    - "db/migrate/20250623163105_add_fee_types_and_replace_output_fee.rb"
    - "db/migrate/20250909132658_create_schedules.rb"
    - "db/migrate/20250909211344_create_milestones.rb"
    - "db/migrate/20250925063550_add_role_to_users.rb"

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Style/Lambda:
  EnforcedStyle: literal

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test
    - sandbox
    - review
    - migration
    - paritycheck

Rails/SkipsModelValidations:
  Enabled: true
  Exclude:
    - spec/support/shared_examples/declarative_updates.rb

Rails/StrongParametersExpect:
  Enabled: true

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/Output:
  Exclude:
    - db/seeds*
    # Excluded because this file intentionally writes a dev-only message to stdout after migrations, which does not
    # impact application behavior and is not intended for production environments.
    - config/initializers/post_migration_erd_prompt.rb

Rails/SaveBang:
  Exclude:
    - app/services/**/*
    - spec/support/shared_examples/metadata_support.rb
    - spec/support/shared_examples/query_avoids_includes.rb

Naming/MethodParameterName:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Capybara/CurrentPathExpectation:
  Exclude:
    - "spec/features/**/*" # Excluded in feature specs because we use Playwright (not Capybara) for those. Leaving it enabled elsewhere in case Capybara matchers are used in other test types.

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/requests/api/docs/**/*'

RSpec/VariableName:
  Exclude:
    - 'spec/requests/api/docs/**/*'
    - 'spec/support/shared_contexts/api_doc_request_auth.rb'
