Style/StringLiterals:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
