---
inherit_from:
  - .rubocop_disabled.yml
  - .rubocop_custom.yml
  - .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-factory_bot

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.4
  StringLiteralsFrozenByDefault: true

require:
  - ./.rubocop/cop/rspec_cops
