---
inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-factory_bot

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.4.4

require:
  - ./.rubocop/cop/rspec_cops

RSpec/RequireRailsHelper:
  Enabled: true
  AutoCorrect: false
  Exclude:
    - "spec/spec_helper.rb"
    - "spec/rails_helper.rb"

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Style/Lambda:
  EnforcedStyle: literal

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test
    - sandbox
    - review
    - migration

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/Output:
  Exclude:
    - db/seeds*

Rails/SaveBang:
  Exclude:
    - app/services/**/*

Naming/MethodParameterName:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Capybara/CurrentPathExpectation:
  Exclude:
    - "spec/features/**/*" # Excluded in feature specs because we use Playwright (not Capybara) for those. Leaving it enabled elsewhere in case Capybara matchers are used in other test types.

RSpec/SpecFilePathFormat:
  Exclude:
    - "spec/components/schools/ects/listing_card_component_spec.rb"

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/requests/api/docs/**/*'
