name: Refresh DB
description: Backup production DB and restore to target environment DB

inputs:
  environment:
    description: The name of the environment
    required: true
  target_environment:
    description: The name of the target environment
    required: true
  exclude-jobs:
    description: Exclude jobs tables
    type: boolean
    default: true
  azure-client-id:
    description: Azure Client ID
    required: true
  azure-tenant-id:
    description: Azure Tenant ID
    required: true
  azure-subscription-id:
    description: Azure Subscription ID
    required: true

runs:
  using: composite

  steps:
    - name: Set Environment variables
      id: set_env_var
      shell: bash
      run: |
        tf_vars_file=config/terraform/application/config/${{ inputs.environment }}.tfvars.json
        echo "NAMESPACE=$(jq -r '.namespace' ${tf_vars_file})" >> $GITHUB_ENV
        if [ "${{ inputs.environment }}" = "migration" ]; then
          echo "DB_INSTANCE=mg" >> $GITHUB_ENV
        else
          echo "DB_INSTANCE=pc" >> $GITHUB_ENV
        fi
        
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
      with:
        azure-client-id: ${{ inputs.azure-client-id }}
        azure-tenant-id: ${{ inputs.azure-tenant-id }}
        azure-subscription-id: ${{ inputs.azure-subscription-id }}

    - name: Install kubectl
      uses: DFE-Digital/github-actions/set-kubectl@master

    - name: Install konduit
      shell: bash
      run: make install-konduit

    - name: Set AKS credentials (production)
      shell: bash
      run: make ci production get-cluster-credentials

    - name: Backup production DB
      shell: bash
      run: |
        # Build up exclude arguments based on flags
        EXCLUDE_ARGS=""

        if [ "${{ inputs.exclude-jobs }}" = "true" ]; then
          EXCLUDE_ARGS="$EXCLUDE_ARGS \
            --exclude-table-data=solid_queue_jobs \
            --exclude-table-data=solid_queue_ready_executions \
            --exclude-table-data=solid_queue_claimed_executions \
            --exclude-table-data=solid_queue_blocked_executions \
            --exclude-table-data=solid_queue_failed_executions \
            --exclude-table-data=solid_queue_processes"
        fi

        echo "Excluding tables (if any): $EXCLUDE_ARGS"

        bin/konduit.sh -n ${{ env.NAMESPACE }} cpd-ec2-${{ inputs.environment }}-web -- pg_dump -E utf8 --compress=1 --clean --if-exists $EXCLUDE_ARGS --no-privileges --no-owner --verbose -f backup-${{ inputs.environment }}.sql.gz

    - name: Restore to ${{ inputs.target_environment }} DB
      shell: bash
      run: bin/konduit.sh -n ${{ env.NAMESPACE }} -d s189p01-cpdec2-${{ env.DB_INSTANCE }}-pg -k s189p01-cpdec2-${{ env.DB_INSTANCE }}-app-kv -i backup-${{ inputs.environment }}.sql.gz -c -t 7200 cpd-ec2-${{ inputs.target_environment }}-web -- psql
