name: Deploy environment to AKS
description: Deploys an application environment to AKS

inputs:
  environment:
    description: The name of the environment
    required: true
  docker-image-tag:
    description: The Docker image tag to deploy
    required: true
  azure-client-id:
    description: Azure service principal or managed identity client ID when using OIDC
    required: true
  azure-subscription-id:
    description: Azure service principal or managed identity subscription ID when using OIDC
    required: true
  azure-tenant-id:
    description: Azure service principal or managed identity tenant ID when using OIDC
    required: true
  pull-request-number:
    description: The pull request number which triggered this deploy. If set, this will automatically seed the database.
    required: false
  statuscake-api-token:
    description: The Statuscake token
    required: false
  commit-sha:
    description: The commit sha for the current commit
    required: true

outputs:
  url:
    description: The base URL for the deployed environment
    value: ${{ steps.apply-terraform.outputs.url }}

runs:
  using: composite

  steps:
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.8
        terraform_wrapper: false

    - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
      with:
        azure-client-id: ${{ inputs.azure-client-id }}
        azure-subscription-id: ${{ inputs.azure-subscription-id }}
        azure-tenant-id: ${{ inputs.azure-tenant-id }}

    - uses: google-github-actions/auth@v2
      with:
        project_id: ecf-bq
        workload_identity_provider: projects/808138694727/locations/global/workloadIdentityPools/register-early-career-teachers-p/providers/register-early-career-teachers-p

    - name: Apply Terraform
      id: apply-terraform
      shell: bash
      run: |
        make ci ${{ inputs.environment }} terraform-apply
        cd config/terraform/application && echo "url=$(terraform output -raw url)" >> $GITHUB_OUTPUT
      env:
        TF_VAR_statuscake_api_token: ${{ inputs.statuscake-api-token }}
        DOCKER_IMAGE_TAG: ${{ inputs.docker-image-tag }}
        PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number }}
        COMMIT_SHA: ${{ inputs.commit-sha }}

    - uses: Azure/login@v2
      with:
        client-id: ${{ inputs.azure-client-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}

    - name: Check for api-seeds label
      id: check_label
      shell: bash
      run: |
        LABELS='${{ toJson(github.event.pull_request.labels) }}'
        echo "Labels: $LABELS"

        if echo "$LABELS" | grep -q '"api-seeds"'; then
          echo "has_label=true" >> $GITHUB_OUTPUT
        else
          echo "has_label=false" >> $GITHUB_OUTPUT
        fi

    - name: Check PR author
      id: check_author
      shell: bash
      run: |
        AUTHOR="${{ github.event.pull_request.user.login }}"
        echo "Author: $AUTHOR"

        API_AUTHORS=("ethax-ross" "cpjmcquillan" "leandroalemao" "mooktakim")

        api_author="false"

        for user in "${API_AUTHORS[@]}"; do
          if [[ "$AUTHOR" == "$user" ]]; then
            api_author="true"
            break
          fi
        done

        echo "api_author=$api_author" >> $GITHUB_OUTPUT

    - name: Run API seed task
      if: (steps.check_label.outputs.has_label == 'true' || steps.check_author.outputs.api_author == 'true') && inputs.pull-request-number != '' && inputs.environment != 'production'
      shell: bash
      run: |
          echo "Running API seeds..."
          make ci review get-cluster-credentials
          kubectl exec -n cpd-development \
            deployment/cpd-ec2-review-${{ inputs.pull-request-number }}-web \
            -- sh -c '
              cd /app &&
              DISABLE_DATABASE_ENVIRONMENT_CHECK=1 \
              RAILS_ENV=${{ inputs.environment }} \
              /usr/local/bin/bundle exec rails db:truncate_all &&
              DISABLE_DATABASE_ENVIRONMENT_CHECK=1 \
              RAILS_ENV=${{ inputs.environment }} \
              /usr/local/bin/bundle exec rake api_seed_data:generate
            '
      env:
        PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number }}

    - name: Run default seed task
      if: inputs.pull-request-number != '' && inputs.environment != 'production'
      shell: bash
      run: |
        echo "Running default seeds..."
        make ci review get-cluster-credentials

        if [[ "${{ steps.check_label.outputs.has_label }}" == "true" || "${{ steps.check_author.outputs.api_author }}" == "true" ]]; then
          COMMAND="rails db:seed"
        else
          COMMAND="rails db:seed:replant"
        fi

        kubectl exec -n cpd-development deployment/cpd-ec2-review-${{ inputs.pull-request-number }}-web -- sh -c "cd /app && DISABLE_DATABASE_ENVIRONMENT_CHECK=1 RAILS_ENV=${{ inputs.environment }} /usr/local/bin/bundle exec $COMMAND"
      env:
        PULL_REQUEST_NUMBER: ${{ inputs.pull-request-number }}
