shared_settings: &shared_settings
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

default: &default
  <<: *shared_settings
  username: "<%= ENV['DB_USERNAME'] %>"
  password: "<%= ENV['DB_PASSWORD'] %>"
  host: "<%= ENV['DB_HOSTNAME'] %>"
  port: "<%= ENV['DB_PORT'] %>"

production_default: &production_default
  database: ecf2_production
  username: ecf2
  password: "<%= ENV['ECF2_DATABASE_PASSWORD'] %>"

development:
  <<: *default
  database: ecf2_development
  # url: "" # Konduit

test:
  <<: *default
  database: ecf2_test

legacy:
  <<: *shared_settings
  url: "<%= ENV['MIGRATION_DATABASE_URL'] || 'postgres://localhost:5432' %>"

review:
  <<: *default
  <<: *production_default

staging:
  <<: *default
  <<: *production_default

sandbox:
  <<: *default
  <<: *production_default

migration:
  <<: *default
  <<: *production_default

production:
  <<: *default
  <<: *production_default
