default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500

  workers:
    # Dedicated critical queues
    - queues: [mailers]
      threads: 2
      processes: 2
      polling_interval: 0.1

    - queues: [default]
      threads: 2
      processes: 2
      polling_interval: 0.1

    # Metadata workers (2 jobs max, will be 2 jobs with 2 workers)
    # The jobs to refresh school metadata have DB-heavy and can
    # lock up the database if we run too many at once.
    - queues: [metadata]
      threads: 1
      processes: 1
      polling_interval: 0.1

    # Everything else
    - queues: [process_batch, trs_sync, events, dfe_analytics, solid_queue_recurring]
      threads: 2
      processes: 2
      polling_interval: 0.1

migration: &migration
  workers:
    # Dedicated critical queues
    - queues: [mailers]
      threads: 2
      processes: 2
      polling_interval: 0.1

    - queues: [default]
      threads: 2
      processes: 2
      polling_interval: 0.1

    # Metadata workers (2 jobs max, will be 2 jobs with 2 workers)
    # The jobs to refresh school metadata have DB-heavy and can
    # lock up the database if we run too many at once.
    - queues: [metadata]
      threads: 1
      processes: 1
      polling_interval: 0.1

    # Everything else
    - queues: [process_batch, trs_sync, events, dfe_analytics, solid_queue_recurring]
      threads: 2
      processes: 2
      polling_interval: 0.1

    # Parity check
    - queues: [parity_check_requests]
      threads: 2
      processes: 2
      polling_interval: 0.1

    # Migration
    - queues: [migration]
      threads: 2
      processes: 2
      polling_interval: 0.1

paritycheck:
  <<: *migration

non_production: &non_production
  workers:
    # Dedicated critical queues
    - queues: [mailers]
      threads: 2
      processes: 2
      polling_interval: 0.1

    - queues: [default]
      threads: 2
      processes: 2
      polling_interval: 0.1

    # Metadata workers (2 jobs max, will be 2 jobs with 2 workers)
    # The jobs to refresh school metadata have DB-heavy and can
    # lock up the database if we run too many at once.
    - queues: [metadata]
      threads: 1
      processes: 1
      polling_interval: 0.1

    # Everything else
    - queues: [process_batch, trs_sync, events, dfe_analytics, solid_queue_recurring]
      threads: 2
      processes: 2
      polling_interval: 0.1

    # API seeds
    - queues: [api_seeds]
      threads: 2
      processes: 2
      polling_interval: 0.1

review:
  <<: *non_production

staging:
  <<: *non_production

sandbox:
  <<: *non_production

development:
  <<: *non_production

test:
  <<: *non_production

production:
  <<: *default
