production:
  refresh_all_metadata_job:
    class: RefreshAllMetadataJob
    args: []
    schedule: every day at 1am
review:
  refresh_all_metadata_job:
    class: RefreshAllMetadataJob
    args: []
    schedule: every day at 1am
