---
ALLOW_INDEXING: false
ENVIRONMENT_COLOUR: orange
ENVIRONMENT_PHASE_BANNER_TAG: Migration 🦔
ENVIRONMENT_PHASE_BANNER_CONTENT: This is the migration environment.
ENABLE_OTP_SCHOOL_SIGN_IN: true
ENABLE_INCIDENT_BANNER: false
ENABLE_MAINTENANCE_BANNER: false
ENABLE_HUBS: false
ENABLE_SENTRY: true
ENABLE_BLAZER: true
ENABLE_FAKE_TRS_API: false
SENTRY_ENVIRONMENT: migration
ENABLE_PERSONAS: false
ENABLE_API: true
SERVICE_URL: "https://cpd-ec2-migration-web.teacherservices.cloud"
DFE_ANALYTICS_ENABLED: false
TRS_API_BASE_URL: "https://preprod.teacher-qualifications-api.education.gov.uk"
TRS_API_VERSION: "20260120"
ENCRYPTION_PRIMARY_KEY: migration_primary_key
ENCRYPTION_DETERMINISTIC_KEY: migration_deterministic_key
ENCRYPTION_DERIVATION_SALT: migration_derivation_salt
RAILS_ENV: migration
ENABLE_TIME_TRAVEL: true
MAX_SESSION_IDLE_TIME: 604800
ENABLE_FINANCE_CONTRACT_PERIODS: true