---
ENVIRONMENT_COLOUR: yellow
ENVIRONMENT_PHASE_BANNER_TAG: Sandbox 🏖️
ENVIRONMENT_PHASE_BANNER_CONTENT: This is the sandbox environment.
ENABLE_SENTRY: true
SENTRY_ENVIRONMENT: sandbox
ENABLE_BLAZER: true
ENABLE_PERSONAS: false
ENABLE_BULK_UPLOAD: false
ENABLE_API: true
DFE_SIGN_IN_API_AUDIENCE: signin.education.gov.uk
DFE_SIGN_IN_API_BASE_URL: 'https://dev-api.signin.education.gov.uk'
DFE_SIGN_IN_CLIENT_ID: RegisterECTs
DFE_SIGN_IN_ISSUER: 'https://dev-oidc.signin.education.gov.uk'
DFE_SIGN_IN_REDIRECT_URI: 'https://sandbox.register-early-career-teachers.education.gov.uk/auth/dfe/callback'
DFE_SIGN_IN_SIGN_OUT_REDIRECT_URI: 'https://sandbox.register-early-career-teachers.education.gov.uk/sign-out'
SERVICE_URL: 'https://sandbox.register-early-career-teachers.education.gov.uk/'
DFE_ANALYTICS_ENABLED: true
TRS_API_BASE_URL: 'https://preprod.teacher-qualifications-api.education.gov.uk'
TRS_API_VERSION: '20250203'
RAILS_ENV: sandbox
