---
ENVIRONMENT_COLOUR: yellow
ENVIRONMENT_PHASE_BANNER_TAG: Lead provider sandbox
ENVIRONMENT_PHASE_BANNER_CONTENT: This sandbox environment is for lead provider testing.
ENABLE_SENTRY: true
ENABLE_FAKE_TRS_API: false
SENTRY_ENVIRONMENT: sandbox
ENABLE_BLAZER: true
ENABLE_PERSONAS: false
ENABLE_SCHOOLS_INTERFACE: true
ENABLE_INCIDENT_BANNER: false
ENABLE_API: true
ENABLE_MIGRATION_TESTING: false
DFE_SIGN_IN_API_AUDIENCE: signin.education.gov.uk
DFE_SIGN_IN_USER_ACCOUNT: "https://pp-services.signin.education.gov.uk/my-services"
DFE_SIGN_IN_API_BASE_URL: "https://pp-api.signin.education.gov.uk"
DFE_SIGN_IN_CLIENT_ID: RegisterECTs
DFE_SIGN_IN_ISSUER: "https://pp-oidc.signin.education.gov.uk"
DFE_SIGN_IN_REDIRECT_URI: "https://sandbox.register-early-career-teachers.education.gov.uk/auth/dfe/callback"
DFE_SIGN_IN_SIGN_OUT_REDIRECT_URI: "https://sandbox.register-early-career-teachers.education.gov.uk/sign-out"
SERVICE_URL: "https://sandbox.register-early-career-teachers.education.gov.uk"
DFE_ANALYTICS_ENABLED: true
TRS_API_BASE_URL: "https://preprod.teacher-qualifications-api.education.gov.uk"
TRS_API_VERSION: "20250203"
RAILS_ENV: sandbox
ENABLE_TRS_TEACHER_REFRESH: false
ENABLE_TIME_TRAVEL: true
MAX_SESSION_IDLE_TIME: 7200
