name: Check data validity

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  check-validity:
    name: Analyse invalid records on migration
    runs-on: ubuntu-latest
    environment: migration
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: Azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
        with:
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - uses: DFE-Digital/github-actions/set-kubectl@master

      - name: Set AKS credentials
        shell: bash
        run: make ci migration get-cluster-credentials

      - name: Truncate and re-run invalidity scan
        shell: bash
        run: |
          kubectl -n cpd-production exec deployment/cpd-ec2-migration-web -- /bin/sh -c '
            cd /app &&
            DISABLE_DATABASE_ENVIRONMENT_CHECK=1 \
            RAILS_ENV=migration \
            /usr/local/bin/bundle exec rails runner "InvalidRecord.delete_all; CheckValidity.new.call"
          '
