name: "Manually deploy an environment"

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: Branch to deploy
        required: true
        default: main
        type: string
      environment:
        description: Deployment environment
        required: true
        default: migration
        type: environment
      pull-request-number:
        description: Pull request number for a review app
        required: false

permissions:
  id-token: write
  packages: write
  pull-requests: write
  security-events: write

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    outputs:
      docker-image-tag: ${{ steps.build-docker-image.outputs.tag }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch-name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DFE-Digital/github-actions/build-docker-image@master
        id: build-docker-image
        with:
          docker-repository: ghcr.io/dfe-digital/register-early-career-teachers-public
          github-token: ${{ secrets.GITHUB_TOKEN }}
          snyk-token: ${{ secrets.SNYK_TOKEN }}

  deploy:
    name: Deploy to environment
    needs: [docker]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch-name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/deploy-environment-to-aks
        id: deploy
        with:
          environment: ${{ inputs.environment }}
          docker-image-tag: ${{ needs.docker.outputs.docker-image-tag }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          statuscake-api-token: ${{ secrets.STATUSCAKE_API_TOKEN }}
          commit-sha: ${{ github.sha }}
          pull-request-number: ${{ inputs.pull-request-number }}
