name: "Deploy"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  contents: read
  id-token: write
  packages: write
  pull-requests: write
  security-events: write

jobs:
  brakeman:
    name: Brakeman
    uses: ./.github/workflows/brakeman.yml

    permissions:
      actions: read
      contents: read
      pull-requests: write
      security-events: write

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  rspec:
    name: RSpec
    uses: ./.github/workflows/rspec.yml

  all-checks-passed:
    name: All checks passed
    needs: [brakeman, lint, rspec]
    runs-on: ubuntu-latest
    steps:
      - run: "echo 'Security checks, linting tests passed, this branch is ready to be merged'"

  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    outputs:
      docker-image-tag: ${{ steps.build-docker-image.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DFE-Digital/github-actions/build-docker-image@master
        id: build-docker-image
        with:
          docker-repository: ghcr.io/dfe-digital/register-early-career-teachers-public
          github-token: ${{ secrets.GITHUB_TOKEN }}
          snyk-token: ${{ secrets.SNYK_TOKEN }}
          max-cache: true

  deploy-review:
    name: Deploy review
    concurrency: deploy_review_${{ github.event.pull_request.number }}
    if: github.actor != 'dependabot[bot]' && github.event_name == 'pull_request'
    needs: docker
    runs-on: ubuntu-latest
    environment:
      name: review
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/deploy-environment-to-aks
        id: deploy
        with:
          environment: review
          docker-image-tag: ${{ needs.docker.outputs.docker-image-tag }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          pull-request-number: ${{ github.event.pull_request.number }}
          commit-sha: ${{ github.event.pull_request.head.sha }}

      - name: Post sticky pull request comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Review app deployed to ${{ steps.deploy.outputs.url }}

  deploy-nonprod:
    name: Deploy to ${{ matrix.environment }} environment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    concurrency: deploy_${{ matrix.environment }}
    needs: [docker, all-checks-passed]
    strategy:
      max-parallel: 1
      matrix:
        environment:
          - staging
          - sandbox
    environment:
      name: ${{ matrix.environment }}
      url: ${{ steps.deploy.outputs.environment_url }}
    outputs:
      environment_url: ${{ steps.deploy.outputs.environment_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/deploy-environment-to-aks
        id: deploy
        with:
          environment: ${{ matrix.environment }}
          docker-image-tag: ${{ needs.docker.outputs.docker-image-tag }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          statuscake-api-token: ${{ secrets.STATUSCAKE_API_TOKEN }}
          commit-sha: ${{ github.sha }}

  deploy-production:
    name: Deploy production
    needs: [docker, deploy-nonprod]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/deploy-environment-to-aks
        id: deploy
        with:
          environment: production
          docker-image-tag: ${{ needs.docker.outputs.docker-image-tag }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          statuscake-api-token: ${{ secrets.STATUSCAKE_API_TOKEN }}
          commit-sha: ${{ github.sha }}

  deploy_domains_infra:
    name: Deploy Domains Infrastructure
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    concurrency: deploy_domains_infra
    needs: [deploy-production]
    environment:
      name: production
    permissions:
      id-token: write

    steps:
    - name: Deploy Domains Infrastructure
      uses: DFE-Digital/github-actions/deploy-domains-infra@master
      with:
        azure-client-id:  ${{ secrets.AZURE_CLIENT_ID }}
        azure-tenant-id:  ${{ secrets.AZURE_TENANT_ID }}
        azure-subscription-id:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
        terraform-base: config/terraform/domains/infrastructure

  deploy_domains_env:
    name: Deploy Domains to ${{ matrix.domain_environment }} environment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    concurrency: deploy_domains_${{ matrix.domain_environment }}
    needs: [deploy_domains_infra]
    strategy:
      max-parallel: 1
      matrix:
        domain_environment: [staging, sandbox, production]
    environment:
      name: production
    permissions:
      id-token: write

    steps:
      - name: Deploy Domains Environment
        uses: DFE-Digital/github-actions/deploy-domains-env@master
        with:
          azure-client-id:  ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id:  ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          environment: ${{ matrix.domain_environment }}
          healthcheck: healthcheck
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          terraform-base: config/terraform/domains/environment_domains
