name: Nightly copy production main db into the snapshot db keeping backup in Azure Storage

on:
  workflow_dispatch:
  schedule:
    - cron: "15 4 * * *" # 04:15 UTC

permissions:
  id-token: write

jobs:
  generate-date:
    runs-on: ubuntu-latest
    outputs:
      today: ${{ steps.get-date.outputs.today }}
    steps:
      - name: Get today's date
        id: get-date
        run: echo "today=$(date +'%F')" >> $GITHUB_OUTPUT

  backup-production-and-store-in-azure-storage:
    uses: ./.github/workflows/backup-db.yml
    needs: generate-date
    with:
      environment: production
      backup-file: cpdec2_production_nightly_copy_${{ needs.generate-date.outputs.today }}
    secrets:
      azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
      azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}

  restore-snapshot-from-azure-storage:
    needs:
      - generate-date
      - backup-production-and-store-in-azure-storage
    uses: ./.github/workflows/restore-snapshot-db-from-azure-storage.yml
    with:
      environment: production
      backup-file: cpdec2_production_nightly_copy_${{ needs.generate-date.outputs.today }}
    secrets:
      azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
      azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
