name: Nightly copy production main db into snapshot db keeping backup in Azure Storage

on:
  workflow_dispatch:
  schedule:
    - cron: "15 4 * * *" # 04:15 UTC

jobs:
  backup-production-and-store-in-azure-storage:
    uses: ./.github/workflows/backup-db.yml
    with:
      environment: production
      backup-file: backup-production.sql

  restore-from-azure-storage:
    uses: ./.github/workflows/restore-snapshot-db-from-azure-storage.yml
    with:
      environment: production
      backup-file: backup-production.sql
