name: Nightly copy production main db into snapshot db keeping no backup in Azure Storage

on:
  workflow_dispatch:
    inputs:
      environment:
        description: GitHub environment to backup and restore
        type: choice
        default: production
        options:
          - staging
          - production
        required: true

  schedule:
    - cron: "15 4 * * *" # 04:15 UTC

jobs:
  backup-and-restore-production:
    runs-on: ubuntu-20.04
    environment:
      name: ${{ inputs.environment || 'production' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Backup and restore snapshot
        uses: ./.github/actions/backup-and-restore-snapshot-database
        with:
          environment: ${{ inputs.environment || 'production' }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
