name: Nightly copy production main db into the snapshot db keeping backup in Azure Storage

on:
  workflow_dispatch:
  schedule:
    - cron: "15 4 * * *" # 04:15 UTC

jobs:
  generate-day_of_week:
    runs-on: ubuntu-latest
    outputs:
      today_day: ${{ steps.get-day.outputs.today_day }}
    steps:
      - name: Get today's day of the week
        id: get-day
        run: echo "today_day=$(date +'%A')" >> $GITHUB_OUTPUT

  backup-production-and-store-in-azure-storage:
    uses: ./.github/workflows/backup-db.yml
    needs: generate-day_of_week
    with:
      environment: production
      backup-file: cpdec2_production_adhoc_${{ needs.generate-day_of_week.outputs.today_day }}
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

  restore-snapshot-from-azure-storage:
    needs:
      - generate-day_of_week
      - backup-production-and-store-in-azure-storage
    uses: ./.github/workflows/restore-snapshot-db-from-azure-storage.yml
    with:
      environment: production
      backup-file: cpdec2_production_adhoc_${{ needs.generate-day_of_week.outputs.today_day }}
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
