name: Nightly copy production main db into the snapshot db keeping backup in Azure Storage

on:
  workflow_dispatch:
  schedule:
    - cron: "15 4 * * *" # 04:15 UTC

jobs:
  backup-production-and-store-in-azure-storage:
    uses: ./.github/workflows/backup-db.yml
    with:
      environment: production
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}

  restore-snapshot-from-azure-storage:
    needs: backup-production-and-store-in-azure-storage
    uses: ./.github/workflows/restore-snapshot-db-from-azure-storage.yml
    with:
      environment: production
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
