name: "Refresh all metadata"

on:
  # TODO: disabled cron for now
  # schedule:
  #   - cron: "0 1 * * *" # Every day at 1 AM UTC
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  refresh_metadata:
    name: "Refresh all metadata"
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: Azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
      with:
        azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
        azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - name: Run refresh all metadata async and track changes
      run: |
        make ci production get-cluster-credentials
        kubectl exec -n cpd-production deployment/cpd-ec2-production-web -- /bin/sh -c "cd /app && bundle exec rails runner 'Metadata::Manager.refresh_all_metadata!(async: true, track_changes: true)'"
